# Generated by Django 3.2.13 on 2022-08-08 11:24

import pathlib

from django.core import (
    serializers,
)
from django.db import (
    migrations,
)


def load_data(apps, schema_editor):
    Employee = apps.get_model('indexes_task_1', 'Employee')
    if not Employee.objects.exists():

        with open(pathlib.Path(__file__).parent.resolve().joinpath('test.json'), 'r') as f:
            data = f.read()

        for obj in serializers.deserialize("json", data):
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indexes_task_1', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
