# Generated by Django 3.2.13 on 2022-08-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes_task_1', '0003_auto_20220814_1812'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='indexes_emp_fname_78e804_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='indexes_emp_iname_d59f47_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='indexes_emp_oname_e6e47e_idx',
        ),
    ]
