# Generated by Django 3.2.13 on 2022-08-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes_task_1', '0004_auto_20220819_1841'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                'CREATE INDEX IF NOT EXISTS fio_idx ON indexes_employees '
                "USING btree ((fname || ' ' || iname || ' ' || oname));"
            ),
            reverse_sql='DROP INDEX IF EXISTS fio_idx;',
        ),
    ]
